application: scorekeepr
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /images
  static_dir: static/images

- url: /css
  static_dir: static/css

- url: /javascripts
  static_dir: static/javascripts

- url: /matches
  script: matches.py

- url: /account
  script: account.py

- url: /.*
  script: dashboard.py