application: scorekeepr
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /images
  static_dir: static/images

- url: /css
  static_dir: static/css

- url: /javascript
  static_dir: static/javascript

- url: /.*
  script: scorekeepr.py